create database projectR;
create table projectR.users ( name varchar(30), dob date, primary key (name));
create user 'lenny'@'%' identified by '1etM3In';
grant select,insert,delete on projectR.users to 'lenny'@'%';
insert into projectR.users values('bruce',"1958-08-07");
insert into projectR.users values('adrian','1957-02-27');
insert into projectR.users values('dave','1956-12-23');
insert into projectR.users values('steve','1956-03-12');
insert into projectR.users values('nicko','1952-06-05');
insert into projectR.users values('janick','1957-01-27');