version: '3'

services:
  database-container:
    build: ./database
    volumes:
      - ./database/data:/var/lib/mysql:rw
#    env_file:
#      - db-vars.environment
    ports:
      - 3307:3306
    restart: 'unless-stopped'

  api-1-service:
    build: ./api
    ports:
      - 5001:5000
    depends_on:
      - database-container
    restart: 'unless-stopped'

  api-2-service:
    build: ./api
    ports:
      - 5002:5000
    depends_on:
      - database-container
    restart: 'unless-stopped'

  api-3-service:
    build: ./api
    ports:
      - 5003:5000
    depends_on:
      - database-container
    restart: 'unless-stopped'

  load-balancer:
    
    build: ./load-balancer

    ports:
      - 5000:5000
      - 8080:8080
    links:
      - api-1-service
      - api-2-service
      - api-3-service
    restart: 'unless-stopped'

